<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <RootNamespace>Desk.Worker</RootNamespace>
    <AssemblyName>Desk.Worker</AssemblyName>
    <UserSecretsId>desk-worker</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\packages\application\Desk.Application.csproj" />
    <ProjectReference Include="..\..\packages\infrastructure\Desk.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Formatting.Compact" />
  </ItemGroup>
</Project>
