using Desk.Application.Attachments;

namespace Desk.Infrastructure.Attachments;

/// <summary>
/// Disk-backed object storage for local mode, so uploaded and imported files survive an API restart
/// alongside the SQLite database and the file secret store. Without it, every attachment row in the
/// local database pointed at bytes that vanished with the process, and downloads 404'd.
///
/// Signed-URL generation is inherited from <see cref="InMemoryObjectStorage"/> so the download
/// contract — and the blob endpoint that verifies it — is byte-for-byte the same in every mode.
/// Production still swaps in a MinIO/S3 implementation behind the same interface.
/// </summary>
public sealed class FileObjectStorage(AttachmentStorageOptions options, TimeProvider clock, string rootPath) : IObjectStorage
{
    private readonly InMemoryObjectStorage _urls = new(options, clock);

    public async Task PutAsync(string key, byte[] data, string contentType, CancellationToken ct = default)
    {
        var path = PathFor(key);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        await File.WriteAllBytesAsync(path, data, ct);
    }

    public async Task<byte[]?> GetAsync(string key, CancellationToken ct = default)
    {
        var path = PathFor(key);
        return File.Exists(path) ? await File.ReadAllBytesAsync(path, ct) : null;
    }

    public Task DeleteAsync(string key, CancellationToken ct = default)
    {
        var path = PathFor(key);
        if (File.Exists(path)) File.Delete(path);
        return Task.CompletedTask;
    }

    public Task<string> PresignGetAsync(string key, TimeSpan ttl, CancellationToken ct = default)
        => _urls.PresignGetAsync(key, ttl, ct);

    /// <summary>
    /// Maps a storage key to a path under the root. Keys are generated by the service (never
    /// user-supplied), but resolve and re-check anyway so a crafted key can never escape the root.
    /// </summary>
    private string PathFor(string key)
    {
        var root = Path.GetFullPath(rootPath);
        var full = Path.GetFullPath(Path.Combine(root, key.Replace('/', Path.DirectorySeparatorChar)));
        if (!full.StartsWith(root + Path.DirectorySeparatorChar, StringComparison.Ordinal))
            throw new InvalidOperationException("Storage key resolved outside the storage root.");
        return full;
    }
}
