# -*- coding: utf-8 -*-
"""Part 4: control panel, reports, assistant, notifications, audit, jobs, public, ops."""
from qa_plan_part1 import mod

mod("17. Client Control Panel",
    "The self-service surface a client administrator uses to manage their own configuration. "
    "Access is per section and per account.",
    [
     ("CP-01", "Capabilities drive the navigation",
      "Open /control-panel as a client admin and as a delegated non-admin.",
      "The admin sees every section; the delegate sees only granted sections.",
      "Browser (two sessions)."),
     ("CP-02", "Ticket instructions, global and per account",
      "Set global instructions, then an override for one account.",
      "The account override wins for that account; others fall back to global.",
      "Open a ticket for each account and compare the amber panel."),
     ("CP-03", "Approvers CRUD",
      "Add, edit and delete an approver.",
      "Each operation persists and is audited.",
      "Browser + SQL + audit log."),
     ("CP-04", "Escalation levels",
      "Create escalation levels and confirm ordering.",
      "Levels persist in order.",
      "Browser."),
     ("CP-05", "Business hours",
      "Set a weekly schedule and save.",
      "Stored as a single row per account with the weekly schedule; reload shows the same values.",
      "Browser + SQL."),
     ("CP-06", "Holidays, manual and imported",
      "Add a holiday by hand, then import from the PSA "
      "(POST /api/control-panel/holidays/import-from-psa).",
      "Imported holidays are de-duplicated BY DATE, so re-importing does not double them and a "
      "renamed holiday does not create a second row.",
      "Run the import twice and compare counts."),
     ("CP-07", "Accounts and devices",
      "View the account card and add a device.",
      "Persists and displays.",
      "Browser."),
     ("CP-08", "Announcements",
      "Create, pin, publish and unpublish an announcement.",
      "Only published announcements are visible to client users; pinned ones sort first.",
      "Browser (two sessions)."),
     ("CP-09", "Knowledge base",
      "Create a draft and a published FAQ article in two categories.",
      "Drafts are hidden from client users; published ones are grouped by category.",
      "Browser."),
     ("CP-10", "Branding",
      "Set display name, logo URL and accent colour.",
      "The live preview updates and the values persist.",
      "Browser. Confirm a javascript: or data: URL in the logo field is REJECTED."),
     ("CP-11", "Account report",
      "Open Control Panel > Reports.",
      "Ticket counts by status, open count, hours logged and billable, and recent tickets - all "
      "matching SQL for that account.",
      "Browser + SQL."),
     ("CP-12", "Open-ticket count uses the mapped statuses",
      "Ensure a ticket carries an unmapped raw provider status, then view the report.",
      "It is NOT counted as open, because the open list is NEW, IN_PROGRESS, WAITING_CUSTOMER, "
      "ON_HOLD. This is why unmapped statuses matter beyond cosmetics.",
      "Browser + SQL. Then map the status and confirm the count corrects itself."),
     ("CP-13", "Delegation scope: one account versus all",
      "Grant a user a section for one account, then for all accounts.",
      "Access matches the scope exactly.",
      "Browser."),
     ("CP-14", "Control panel is client-only",
      "Attempt /api/control-panel/* with a staff-only session.",
      "Refused.",
      "API."),
    ])

mod("18. Reports, Export and Scheduling",
    "CSV export plus scheduled report runs delivered for in-portal download.",
    [
     ("RPT-01", "CSV export is valid",
      "GET /api/control-panel/report/export.",
      "RFC-4180 compliant: quoted fields, escaped quotes, correct header. Opens cleanly in Excel.",
      "Download and open. Include a client name containing a comma and a quote."),
     ("RPT-02", "Create a schedule",
      "PUT /api/control-panel/report/schedules with a frequency.",
      "Stored with the correct next-run time.",
      "SQL on report_schedules."),
     ("RPT-03", "Run now",
      "POST /api/control-panel/report/schedules/{id}/run.",
      "A run is recorded and the file is downloadable.",
      "Browser + SQL on report_runs."),
     ("RPT-04", "Scheduled runs fire",
      "Set a schedule due in the past and wait for the worker's 5-minute tick.",
      "The run executes once and the next-run time advances.",
      "SQL + worker log. Confirm it does not run repeatedly."),
     ("RPT-05", "Run history and download",
      "GET /api/control-panel/report/runs then download one.",
      "History lists past runs; each downloads its own CSV.",
      "Browser."),
     ("RPT-06", "No email is sent",
      "Inspect the delivery path.",
      "There is no SMTP in the stack: reports and enquiries are STORED for in-portal download, "
      "never emailed. Verify expectations match this.",
      "Code/config review - this is a design fact worth confirming with the customer."),
    ])

mod("19. AI Assistant",
    "Gemini-backed, OFF per tenant by default, and it must never send internal notes unless "
    "explicitly enabled.",
    [
     ("AI-01", "Disabled by default",
      "Open a ticket on a tenant that has never configured the assistant.",
      "No assistant actions are offered.",
      "Browser."),
     ("AI-02", "Enabling without a key is refused",
      "Attempt to enable the assistant with no API key stored.",
      "Refused with a clear message.",
      "Browser + API."),
     ("AI-03", "The key is never returned",
      "GET /api/assistant/settings.",
      "Returns hasKey true/false only - never the key itself.",
      "Raw JSON."),
     ("AI-04", "Internal notes are excluded by default",
      "With IncludeInternalNotes false, run Summarise on a ticket containing internal notes.",
      "Internal content is not sent, and the prompt STATES the exclusion.",
      "Inspect the outbound request in the API log/telemetry. This is a confidentiality control, "
      "not a preference."),
     ("AI-05", "All six actions work",
      "Run Summarise, DraftReply, ImproveDraft, NextSteps, ExplainError and SimilarTickets.",
      "Each returns a useful result into the composer.",
      "Browser."),
     ("AI-06", "The assistant writes nothing",
      "Run every action and then inspect the ticket.",
      "No note, status change or time entry is created - drafts land in the composer only.",
      "SQL before/after."),
     ("AI-07", "Provider errors are translated",
      "Configure a deliberately invalid key and run an action.",
      "401/403 becomes 'check the key', 429 becomes 'wait', and 400 shows the provider's own "
      "message.",
      "Browser."),
     ("AI-08", "Ticket scope is checked before the model is called",
      "Request an assistant action for a ticket the user may not see.",
      "Refused BEFORE any call to the provider.",
      "API + absence of an outbound request in the log."),
    ])

mod("20. Notifications, Audit and Background Jobs",
    "Operational surfaces an administrator relies on when something goes wrong.",
    [
     ("OPS-01", "Notification list and history",
      "GET /api/me/notifications and /notifications/history.",
      "Own-data sections are visible to every authenticated user regardless of role.",
      "Browser as a Technician."),
     ("OPS-02", "Audit trail is written",
      "Perform a connection edit, a role change and a mapping change.",
      "Each appears in /dashboard/audit with actor, action and target.",
      "Browser + SQL on audit_logs."),
     ("OPS-03", "Audit records no secrets",
      "Rotate a credential and inspect the audit entry.",
      "The entry records that a rotation happened, with no credential value.",
      "SQL on the audit payload."),
     ("OPS-04", "Audit is append-only",
      "Attempt to modify or delete an audit row through the application.",
      "No such path exists.",
      "API surface review."),
     ("OPS-05", "Job list and dead-letter queue",
      "Open /dashboard/jobs.",
      "Queued, running, failed and DLQ jobs are listed with their attempt counts.",
      "Browser + SQL."),
     ("OPS-06", "Reprocess a dead-lettered job",
      "POST /api/admin/jobs/{id}/reprocess on a DLQ job, then on a non-DLQ job.",
      "The DLQ job is re-queued and audited; the non-DLQ one is refused.",
      "API + SQL."),
     ("OPS-07", "Retry and backoff",
      "Force a transient failure in a job handler.",
      "It retries with backoff and lands in the DLQ only after the configured attempts.",
      "Worker log + SQL."),
     ("OPS-08", "Storage usage",
      "GET /api/admin/storage.",
      "Reported usage matches actual attachment storage.",
      "API + storage inspection."),
    ])

mod("21. Public Site, Enquiries and Legal",
    "The marketing surface and the only anonymous write path in the system.",
    [
     ("PUB-01", "Marketing pages render",
      "Visit /, /about, /faq, /contact, /book, /platform, /security, /integrations and every "
      "/features/{slug}.",
      "All render with no console errors and no broken links.",
      "Browser DevTools."),
     ("PUB-02", "Contact enquiry is stored",
      "Submit the contact form.",
      "A row appears in enquiries and in /dashboard/enquiries. Nothing is emailed - by design.",
      "Browser + SQL."),
     ("PUB-03", "Meeting request",
      "Submit the booking form.",
      "Stored and visible to staff with enquiries.view.",
      "Browser."),
     ("PUB-04", "Honeypot silently absorbs bots",
      "POST /api/public/enquiries/contact with the 'website' field filled.",
      "Returns 202 and stores NOTHING.",
      "curl + SQL count unchanged."),
     ("PUB-05", "Enquiry validation",
      "Submit with a missing required field and with an oversized payload.",
      "Rejected with a validation error, never a 500.",
      "curl. A required attribute on a positional record parameter has twice caused a 500 on "
      "every request - this is the guard test."),
     ("PUB-06", "Enquiry status workflow",
      "POST /api/admin/enquiries/{id}/status.",
      "Status updates and is audited.",
      "Browser."),
     ("PUB-07", "Legal pages complete",
      "Open /privacy and /terms.",
      "Both render with working anchors. CHECK for unfilled placeholder slots - registered "
      "address, hosting region, retention periods, liability cap and governing law were left "
      "deliberately blank for the owner to supply.",
      "Browser. Shipping these with placeholders visible to customers is a real risk."),
     ("PUB-08", "No cookie banner is needed",
      "Inspect cookies on the public site.",
      "Session cookies only, no analytics - which is why no consent banner is present. Confirm "
      "this is still true before adding any third-party script.",
      "DevTools > Application > Cookies."),
    ])

mod("22. Performance, Scale and Resilience",
    "How the system behaves as the desk grows, and what to watch.",
    [
     ("PERF-01", "Full re-sync duration is known",
      "Time a full re-sync: set LastSuccessfulSyncAt to null and watch until the timestamp "
      "returns.",
      "Record the duration against the ticket count. It scales roughly linearly because each "
      "ticket triggers note import, assignee resolution and a time refresh.",
      "SQL timestamps. At 135 tickets this is 15-20 minutes; plan accordingly at 1,000+."),
     ("PERF-02", "Incremental sync stays cheap",
      "Observe a quiet 5-minute cycle.",
      "Only changed tickets are processed; a no-op cycle logs nothing and simply advances the "
      "timestamp.",
      "Worker log + SQL."),
     ("PERF-03", "Page cap headroom",
      "Compare the ticket count in range with 50 pages x 100 per page.",
      "Comfortably under 5,000. Beyond that the cap truncates - and now warns.",
      "SQL + log."),
     ("PERF-04", "Ticket list performance",
      "Load the ticket list for the largest client.",
      "Loads within an acceptable time; the supporting indexes are in place.",
      "Browser timing + EXPLAIN on the query."),
     ("PERF-05", "Concurrent users",
      "Have several testers use the portal simultaneously during a sync.",
      "No deadlocks or timeouts; the rollup's batched deletes do not block dashboard reads.",
      "Observation + database locks."),
     ("PERF-06", "Recovery after an outage",
      "Stop the PSA connection (or the database) briefly, then restore it.",
      "The worker resumes on the next cycle without manual intervention, and a failed pass "
      "repairs itself rather than leaving a permanent hole.",
      "Worker log."),
    ])

mod("23. Regression Traps - Defects Already Found in This Build",
    "Every item here is a real bug that shipped, was fixed, and would be easy to reintroduce. "
    "Re-run these after any change to the sync, mapping or connector code.",
    [
     ("REG-01", "Sync imports EVERY ticket, not the first page",
      "Full re-sync with more tickets than the page size.",
      "Count matches the PSA. Regression symptom: exactly 100 (or N x 100) tickets.",
      "SQL vs PSA count."),
     ("REG-02", "Every written field is in the update hash",
      "Change one field at a time in the PSA and sync.",
      "Each change lands. Regression symptom: a field that never updates on existing rows while "
      "new tickets look correct.",
      "SQL per field. Has occurred for the raise date and for the queue."),
     ("REG-03", "Mapping actually maps",
      "After any connector change, check PsaStatus versus PortalStatus.",
      "They differ wherever a rule exists. Regression symptom: PsaStatus = PortalStatus on every "
      "row, which looks exactly like a deliberate pass-through.",
      "SQL."),
     ("REG-04", "Discovery offers what tickets arrive with",
      "Save a mapping through the UI, then sync.",
      "The saved rule matches incoming tickets. Regression symptom: rules hold ids while tickets "
      "carry names.",
      "SQL + the certification tests."),
     ("REG-05", "Autotask next page is POSTed",
      "Full Autotask re-sync spanning more than one page.",
      "No 405 'does not support http method GET'.",
      "Worker log."),
     ("REG-06", "Note title does not duplicate the body",
      "Post a long note to Autotask.",
      "Rendered once.",
      "Autotask UI."),
     ("REG-07", "Internal notes are not dropped",
      "Autotask time entry with internal-only text.",
      "Text preserved.",
      "Portal thread."),
     ("REG-08", "Retired picklist values are filtered",
      "Retire a value in the PSA and refresh fields.",
      "Not offered; existing rules flagged.",
      "Browser."),
     ("REG-09", "Rollup builds history, not just the last week",
      "Insert an event older than seven days and run the rollup.",
      "A fact is created for it.",
      "SQL."),
     ("REG-10", "Fakes must not be more permissive than the real API",
      "When adding connector behaviour, make the in-memory fake enforce what the provider "
      "enforces.",
      "The unit suite fails before production does. Every connector bug in this list was hidden "
      "at least once by a fake that accepted something the real API rejects.",
      "dotnet test tests/unit."),
    ])
