# -*- coding: utf-8 -*-
"""Part 2: connections, mapping, sync, tickets, notes, time."""
from qa_plan_part1 import mod

mod("7. Client Users and the Client Portal",
    "Client-side accounts are client_users rows, distinct from staff app_users. A person holding "
    "both identities must resolve as staff.",
    [
     ("CLIENT-01", "Invite a client user",
      "/control-panel/users > invite, or POST /api/control-panel/users.",
      "Invited user appears with the correct company and no staff permissions.",
      "Browser + SQL: select * from client_users order by \"CreatedAt\" desc limit 1."),
     ("CLIENT-02", "Import contacts from the PSA",
      "Control Panel > Accounts > Import from PSA "
      "(POST /api/control-panel/import-from-psa).",
      "PSA contacts become client_users with their real email addresses.",
      "Browser + SQL count before/after."),
     ("CLIENT-03", "Client can raise a ticket",
      "As a client user, create a ticket from the portal.",
      "Ticket is created in the PSA first, then stored locally with a portal-origin sync event.",
      "Portal + PSA UI. Confirm the ticket exists in the PSA, not only in the portal."),
     ("CLIENT-04", "Client can reply but not use staff tooling",
      "Open a ticket as a client user.",
      "Reply box present. No time panel, no assignment control, no internal-note toggle; the "
      "status is a static badge.",
      "Browser."),
     ("CLIENT-05", "Client thread sides and attribution",
      "View a thread containing both client and staff notes.",
      "Client messages left, staff right, with correct author names.",
      "Browser. Notes imported before FromClient was captured keep their old side until "
      "re-imported - do not report that as a new bug."),
     ("CLIENT-06", "Section delegation",
      "Grant a non-admin client user access to only the Instructions section for one account.",
      "That user sees Instructions for that account and nothing else.",
      "Browser as that user."),
     ("CLIENT-07", "Last client admin cannot be removed",
      "Attempt to deactivate the only client administrator for a company.",
      "Refused.",
      "Browser."),
     ("CLIENT-08", "Client cannot see another company",
      "As a client user of company X, request a ticket belonging to company Y.",
      "Refused.",
      "API."),
    ])

mod("8. PSA Connections",
    "Two live connectors: Autotask (REST v1.0, numeric picklists) and ConnectWise Manage "
    "(REST 3.0, board-scoped statuses).",
    [
     ("CONN-01", "Create a connection",
      "/dashboard/connections > Add. Enter endpoint and credentials. NOTE: the tester enters "
      "credentials themselves - never paste them into a chat or a ticket.",
      "Connection saved; credentials go to the encrypted secret store and only a reference is on "
      "the row.",
      "SQL: select \"CredentialSecretRef\" from psa_connections - it is a reference, not a secret."),
     ("CONN-02", "Test connection",
      "POST /api/admin/connections/{id}/test.",
      "Status becomes Healthy on success; a wrong credential yields the provider's own error "
      "message, not a generic 500.",
      "Browser + API. Deliberately break a credential to see the real message."),
     ("CONN-03", "Credential rotation merges rather than clobbers",
      "Edit a connection and change ONLY one credential field, leaving the others blank.",
      "Typed values are merged over stored ones; untouched fields are preserved.",
      "Re-run Test connection - it must still succeed."),
     ("CONN-04", "Per-field stored-credential chips",
      "Open the edit form for a configured connection.",
      "Each credential field shows Stored or Nothing stored. No secret value is displayed.",
      "Browser."),
     ("CONN-05", "Enable / disable",
      "POST /api/admin/connections/{id}/enabled false.",
      "Sync stops for that connection; the UI shows it disabled; no errors are logged.",
      "Worker log - no further PSA calls for that connection."),
     ("CONN-06", "Field discovery",
      "POST /api/admin/connections/{id}/fields/refresh then GET .../fields.",
      "Boards/queues, statuses, priorities, categories, work types, work roles and technicians "
      "come back populated.",
      "API. Compare option counts against the PSA UI."),
     ("CONN-07", "Retired picklist values are excluded",
      "Retire a status in the PSA, refresh fields, and open the mapping page.",
      "The retired value no longer appears as a selectable option, and any rule still pointing at "
      "it shows red 'Not accepted by PSA' rather than green Mapped.",
      "Browser. This is a real defect class - retired values saved fine and were rejected on "
      "every write."),
     ("CONN-08", "Discovery offers two representations",
      "Inspect GET /api/admin/connections/{id}/fields for queuesOrBoards.",
      "Each option carries value (the id, sent TO the provider) and syncValue (the name, what "
      "tickets ARRIVE with). For queues these differ.",
      "Raw JSON. This split is what makes mapping and filtering both work."),
     ("CONN-09", "Import filters",
      "Set FilterQueueIds / FilterCompanyIds / FilterActiveWithinDays and run a sync.",
      "Only matching tickets are imported. Filters are applied provider-side AND re-applied "
      "client-side so both connectors behave identically.",
      "SQL ticket count + worker log."),
     ("CONN-10", "Include closed tickets toggle",
      "Turn ImportClosedTickets off, force a full re-sync, then on again.",
      "Closed tickets are excluded then included. Closed rows already imported keep their data.",
      "SQL: count(*) filter (where \"ClosedAt\" is not null)."),
     ("CONN-11", "Time entry readiness check",
      "POST /api/admin/connections/{id}/check-time-entry.",
      "Autotask reports by name: no technician set / technician gone / holds no active role / "
      "configured role not held (listing the roles they DO hold) / Ready. No time entry is created.",
      "API + SQL: confirm no new time entry row exists."),
     ("CONN-12", "Sync now",
      "POST /api/admin/connections/{id}/sync.",
      "A sync runs immediately and the result is reported.",
      "Worker/API log."),
     ("CONN-13", "Connection health page",
      "Open /dashboard/health.",
      "Shows last successful sync, last health check and last error per connection, matching SQL.",
      "Browser + SQL on psa_connections."),
     ("CONN-14", "Failure marks the connection degraded",
      "Temporarily point a connection at an unreachable endpoint and let a sync run.",
      "Status becomes Failed/Degraded with the real reason in LastError, and the loop keeps "
      "running for the other connection.",
      "SQL + worker log."),
    ])

mod("9. Field Mapping",
    "Translates provider values to the portal vocabulary and back. The portal statuses are NEW, "
    "IN_PROGRESS, WAITING_CUSTOMER, ON_HOLD, RESOLVED, CLOSED; priorities LOW, NORMAL, HIGH, "
    "CRITICAL. Queue and category are free-form.",
    [
     ("MAP-01", "Mapping page lists live options",
      "Open /dashboard/mappings, pick a connection and the status tab.",
      "Options come from live discovery, showing human labels.",
      "Browser."),
     ("MAP-02", "A saved rule matches an incoming ticket",
      "Save a status mapping through the UI, then force a re-sync.",
      "Tickets in that status show the mapped PORTAL value.",
      "SQL: select \"PsaStatus\",\"PortalStatus\" ... - THE KEY CHECK IS THAT THEY DIFFER. "
      "PsaStatus = PortalStatus on every row means nothing is mapping at all."),
     ("MAP-03", "Unmapped provider values are reported",
      "Move a ticket in the PSA into a status with no rule, then sync.",
      "The worker logs a warning naming provider, field and value, once per run.",
      "docker logs desk-portal-prod-worker-1 | grep 'No mapping rule matches'. Silence here used "
      "to mean the bug was invisible."),
     ("MAP-04", "Unmapped values fall through, they do not crash",
      "Same as MAP-03.",
      "The ticket still imports, carrying the provider's raw value.",
      "SQL."),
     ("MAP-05", "Inbound ambiguity is prevented",
      "Run the ambiguity query after any mapping change: select \"PsaConnectionId\",\"PortalField\","
      "\"ExternalValue\",count(*) from field_mappings where \"IsActive\" and \"Direction\" in (2,3) "
      "group by 1,2,3 having count(*)>1;",
      "Zero rows. Two inbound rules on one provider value resolve non-deterministically.",
      "SQL. Run the mirror query for outbound: Direction in (1,3) grouped by PortalValue."),
     ("MAP-06", "Direction is honoured",
      "Create a ProviderToPortal-only rule and push a change from the portal.",
      "The inbound-only rule is not used outbound.",
      "PSA UI - confirm the pushed value came from the bidirectional rule."),
     ("MAP-07", "Two portal values sharing one provider value",
      "Map RESOLVED and CLOSED both to the same provider status.",
      "Exactly one is Bidirectional and the other PortalToProvider, so inbound is deterministic.",
      "SQL + an inbound sync of a closed ticket."),
     ("MAP-08", "Autotask numeric picklists resolve",
      "Change a ticket status from the portal on an Autotask ticket.",
      "The label is resolved to the numeric id before the write; no 'Could not convert string to "
      "integer' error.",
      "PSA UI + API response."),
     ("MAP-09", "ConnectWise board-scoped statuses",
      "Change status on ConnectWise tickets that live on different boards.",
      "The status name resolves against each ticket's OWN board.",
      "PSA UI. An id from another board must produce a clear error naming the available statuses."),
     ("MAP-10", "Statuses from every board are offered",
      "On ConnectWise, confirm the status dropdown includes a status that exists only on a second "
      "board.",
      "Present. Reading only the first board hides statuses tickets genuinely arrive in.",
      "Browser."),
     ("MAP-11", "Queue and category mapping",
      "Map a provider queue name to a different portal name and re-sync.",
      "Tickets display the portal name.",
      "SQL on tickets.\"QueueOrBoard\"."),
     ("MAP-12", "Mapping change reaches tickets already imported",
      "Change a queue or status mapping, then force a re-sync.",
      "EXISTING tickets update, not only new ones.",
      "SQL before/after. If nothing changes, the field is missing from the update hash - that "
      "exact bug has occurred three times."),
     ("MAP-13", "Version snapshot and rollback",
      "Change a mapping, then GET /api/admin/mappings/versions and roll back.",
      "The prior rule set is restored exactly.",
      "API + SQL. field_mapping_versions.SnapshotJson is also the recovery path after a bad "
      "direct SQL edit."),
     ("MAP-14", "Direct SQL edits must be connection-scoped",
      "If editing mappings in SQL, always include PsaConnectionId and check the reported row "
      "count against what you expected.",
      "Row count matches expectation exactly.",
      "psql. An UPDATE without PsaConnectionId hits BOTH connections - this has happened."),
     ("MAP-15", "Work type mapping",
      "Map a portal work type to a provider work type and log time using it.",
      "The PSA time entry carries the mapped work type.",
      "PSA UI."),
     ("MAP-16", "Mapping rules take effect without a restart",
      "Edit a rule in the database, then wait for the next sync tick.",
      "The new rule applies - rules are read fresh from the database each run, with no cache.",
      "SQL + worker behaviour. Note such edits bypass the version snapshot and audit trail."),
    ])

mod("10. Ticket Sync Engine",
    "The heart of the product: incremental and full sync, pagination, idempotency, echo "
    "suppression and lifecycle dates.",
    [
     ("SYNC-01", "First import creates tickets and companies",
      "Point a connection at a PSA with tickets and run a full sync.",
      "Tickets imported and client companies auto-created for unknown company ids.",
      "SQL counts on tickets and client_companies."),
     ("SYNC-02", "Pagination reads past the first page",
      "Ensure the PSA has more tickets in range than the page size (100), then force a full "
      "re-sync with: update psa_connections set \"LastSuccessfulSyncAt\"=NULL;",
      "ALL tickets import, not the first 100. Autotask follows nextPageUrl; ConnectWise pages by "
      "number ordered by id.",
      "SQL count vs the PSA's own count. This bug silently cost 34 of 135 tickets."),
     ("SYNC-03", "Page boundaries do not skip or duplicate",
      "After SYNC-02, check for duplicates.",
      "select \"ExternalTicketId\",count(*) from tickets group by 1 having count(*)>1 returns "
      "nothing, and the total matches the PSA.",
      "SQL."),
     ("SYNC-04", "Page cap is reported, not silent",
      "If a run hits the 50-page safety cap, the worker warns.",
      "A warning naming the connection appears; the run is known to be incomplete.",
      "grep 'safety cap' in the worker log."),
     ("SYNC-05", "Unchanged ticket is skipped",
      "Run two syncs back to back with no PSA changes.",
      "The second reports no updates - the update hash short-circuits.",
      "Worker log / sync result."),
     ("SYNC-06", "A changed field always reaches an existing row",
      "Change ONE field in the PSA (status, priority, title, queue, or a date) and sync.",
      "The portal row updates. Every field the sync writes must be in the state hash.",
      "SQL per field. Test the queue and the lifecycle dates specifically - both have failed here."),
     ("SYNC-07", "Portal echo is suppressed",
      "Change a status from the portal, then let the next sync run.",
      "The change coming back from the PSA is recognised as our own and does not re-trigger "
      "an update or a duplicate activity event.",
      "SQL on sync_events + activity_events counts."),
     ("SYNC-08", "Lifecycle dates are captured",
      "Sync tickets that are open, resolved and closed.",
      "PsaCreatedAt (raise date), ResolvedAt, ClosedAt and SlaDueAt populate where the provider "
      "supplies them.",
      "SQL: select count(*), count(\"PsaCreatedAt\"), count(\"ClosedAt\"), count(\"SlaDueAt\") "
      "from tickets."),
     ("SYNC-09", "Raise date is the PSA date, not the import date",
      "Compare PsaCreatedAt with the ticket's created date in the PSA.",
      "They match. The row's own CreatedAt is the import time and must not be used as ticket age.",
      "SQL vs PSA UI."),
     ("SYNC-10", "Absent is distinguished from empty",
      "Check a ConnectWise open ticket.",
      "ClosedAt is null because the provider omits the field while the ticket is open - not "
      "because the mapping is wrong. Do not fill it with lastUpdated.",
      "SQL + the connector's field-shape log line."),
     ("SYNC-11", "Notes import both ways",
      "Add a public and an internal note in the PSA, then sync.",
      "Both import with the correct IsPublic flag and author side.",
      "Portal thread + SQL on ticket_notes."),
     ("SYNC-12", "Time-entry notes are included",
      "Add a note on a PSA time entry.",
      "It appears in the portal thread as internal, keyed te-{id}.",
      "Portal thread."),
     ("SYNC-13", "Deletion reconciliation",
      "Delete a note in the PSA and sync.",
      "The portal removes it - but only provider-origin notes; portal-authored notes are never "
      "reconciled away.",
      "SQL on ticket_notes before/after."),
     ("SYNC-14", "Unsynced tickets are visible and re-syncable",
      "GET /api/admin/tickets/unsynced, then POST /api/admin/tickets/{id}/resync.",
      "Failed rows are listed with their error and can be retried individually.",
      "Browser + API."),
     ("SYNC-15", "A failing connection does not stop the other",
      "Break connection A's credentials and let a cycle run.",
      "Connection B still syncs; A is marked with its error.",
      "Worker log + SQL."),
     ("SYNC-16", "Sync completion signal",
      "To confirm a sync ran, watch psa_connections.\"LastSuccessfulSyncAt\" move.",
      "The timestamp advances. Do NOT poll the log for a 'Synced ...' line: it is only written "
      "when something changed, and docker logs --since still contains earlier runs.",
      "SQL. This exact mistake produced three false verifications in one day."),
    ])
